# 1 Import libraries

In [32]:
import pandas as pd
import numpy as np

#2 Upload the raw CSV

In [33]:
from google.colab import files
raw_path = "raw_customer_transactions.csv"
df = pd.read_csv(raw_path)

#3 Preview the dataset

In [34]:
df.head()

,InvoiceNo,CustomerID,InvoiceDate,Quantity,UnitPrice,DiscountPercent,Revenue,ProductCategory,Country,Region,AcquisitionChannel,SubscriptionPlan,OrderStatus,PaymentMethod
0,INV100001,C00001,2025-12-13,1,561.28,0,561.28,Software,India,East,Organic Search,Basic,Cancelled,Credit Card
1,INV100002,C00001,2026-01-05,3,167.05,15,425.98,Education,India,East,Organic Search,Basic,Completed,Net Banking
2,INV100003,C00001,2026-01-01,4,477.13,15,1622.24,Software,India,East,Organic Search,Basic,Completed,Debit Card
3,INV100004,C00002,2026-02-06,1,562.38,5,534.26,Books,United Kingdom,North,Referral,Basic,Completed,UPI
4,INV100005,C00002,2026-02-08,2,558.93,0,1117.86,Books,United Kingdom,North,Referral,Basic,Completed,Debit Card

In [35]:
df.shape

(4140, 14)

In [36]:
df.columns

Index(['InvoiceNo', 'CustomerID', 'InvoiceDate', 'Quantity', 'UnitPrice',
       'DiscountPercent', 'Revenue', 'ProductCategory', 'Country', 'Region',
       'AcquisitionChannel', 'SubscriptionPlan', 'OrderStatus',
       'PaymentMethod'],
      dtype='object')

#4 Inspect data types

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4140 entries, 0 to 4139
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   InvoiceNo           4140 non-null   object
 1   CustomerID          4096 non-null   object
 2   InvoiceDate         4140 non-null   object
 3   Quantity            4140 non-null   int64
 4   UnitPrice           4140 non-null   float64
 5   DiscountPercent     4140 non-null   int64
 6   Revenue             4140 non-null   float64
 7   ProductCategory     4140 non-null   object
 8   Country             4140 non-null   object
 9   Region              4140 non-null   object
 10  AcquisitionChannel  4140 non-null   object
 11  SubscriptionPlan    4140 non-null   object
 12  OrderStatus         4140 non-null   object
 13  PaymentMethod       4140 non-null   object
dtypes: float64(2), int64(2), object(10)
memory usage: 452.9+ KB

In [38]:
df.dtypes

InvoiceNo              object
CustomerID             object
InvoiceDate            object
Quantity                int64
UnitPrice             float64
DiscountPercent         int64
Revenue               float64
ProductCategory        object
Country                object
Region                 object
AcquisitionChannel     object
SubscriptionPlan       object
OrderStatus            object
PaymentMethod          object
dtype: object

#5 Check missing values

In [39]:
df.isnull().sum()

InvoiceNo              0
CustomerID            44
InvoiceDate            0
Quantity               0
UnitPrice              0
DiscountPercent        0
Revenue                0
ProductCategory        0
Country                0
Region                 0
AcquisitionChannel     0
SubscriptionPlan       0
OrderStatus            0
PaymentMethod          0
dtype: int64

In [40]:
(df.isnull().sum() / len(df) * 100).round(2)

InvoiceNo             0.00
CustomerID            1.06
InvoiceDate           0.00
Quantity              0.00
UnitPrice             0.00
DiscountPercent       0.00
Revenue               0.00
ProductCategory       0.00
Country               0.00
Region                0.00
AcquisitionChannel    0.00
SubscriptionPlan      0.00
OrderStatus           0.00
PaymentMethod         0.00
dtype: float64

# 6 Check duplicate rows

In [41]:
df.duplicated().sum()

np.int64(33)

In [42]:
df = df.drop_duplicates().copy()

In [43]:
df.duplicated().sum()

np.int64(0)

#7 Remove missing CustomerID

In [44]:
df = df.dropna(subset=["CustomerID"]).copy()

In [45]:
df["CustomerID"] = df["CustomerID"].astype(str).str.strip()

df = df[
    (df["CustomerID"] != "") &
    (df["CustomerID"].str.lower() != "nan")
].copy()

#8 Clean text columns

In [46]:
text_columns = [
    "InvoiceNo",
    "CustomerID",
    "ProductCategory",
    "Country",
    "Region",
    "AcquisitionChannel",
    "SubscriptionPlan",
    "OrderStatus",
    "PaymentMethod"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

#9 Convert InvoiceDate correctly

In [47]:
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce",
    dayfirst=True
)

/tmp/ipykernel_616/2926293107.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["InvoiceDate"] = pd.to_datetime(

In [48]:
df["InvoiceDate"].isna().sum()

np.int64(23)

In [49]:
df = df.dropna(subset=["InvoiceDate"]).copy()

#10 Convert numeric columns

In [50]:
numeric_columns = [
    "Quantity",
    "UnitPrice",
    "DiscountPercent",
    "Revenue"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [51]:
df[numeric_columns].isnull().sum()

Quantity           0
UnitPrice          0
DiscountPercent    0
Revenue            0
dtype: int64

#11 Remove cancelled and refunded orders

In [52]:
df["OrderStatus"].value_counts(dropna=False)

OrderStatus
Completed    3697
Cancelled     181
Refunded      162
Name: count, dtype: int64

In [53]:
df = df[
    df["OrderStatus"].str.lower() == "completed"
].copy()

#12 Remove invalid quantities

In [54]:
df["Quantity"].describe()

count    3697.000000
mean        2.938058
std         1.416394
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Quantity, dtype: float64

In [55]:
df = df[df["Quantity"] > 0].copy()

#13 Remove invalid **UnitPrice**

In [56]:
df["UnitPrice"].describe()

count    3697.000000
mean     1260.501136
std      1149.013873
min         0.000000
25%       465.680000
50%       832.760000
75%      1625.930000
max      5914.590000
Name: UnitPrice, dtype: float64

In [57]:
df = df[df["UnitPrice"] > 0].copy()

#13 Remove invalid UnitPrice

In [58]:
df["UnitPrice"].describe()

count    3682.000000
mean     1265.636257
std      1148.525942
min       111.100000
25%       470.272500
50%       835.520000
75%      1628.997500
max      5914.590000
Name: UnitPrice, dtype: float64

In [59]:
df = df[df["UnitPrice"] > 0].copy()

#14 Validate discounts

In [60]:
df["DiscountPercent"].value_counts().sort_index()

DiscountPercent
0     1739
5      732
10     616
15     366
20     229
Name: count, dtype: int64

In [61]:
df = df[
    df["DiscountPercent"].between(0, 100)
].copy()

#15 Recalculate Revenue

In [62]:
df["Revenue"] = (
    df["Quantity"] *
    df["UnitPrice"] *
    (1 - df["DiscountPercent"] / 100)
)

In [63]:
df["Revenue"] = df["Revenue"].round(2)

In [64]:
df = df[df["Revenue"] > 0].copy()

#16 Standardize CustomerID

In [65]:
df["CustomerID"] = (
    df["CustomerID"]
    .astype(str)
    .str.replace(".0", "", regex=False)
    .str.strip()
)

#17 Create TransactionMonth

In [66]:
df["TransactionMonth"] = (
    df["InvoiceDate"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

#18 Create CohortMonth

In [67]:
df["CohortMonth"] = (
    df.groupby("CustomerID")["TransactionMonth"]
    .transform("min")
)

#19 Create CohortIndex

In [68]:
df["CohortIndex"] = (
    (df["TransactionMonth"].dt.year - df["CohortMonth"].dt.year) * 12
    +
    (df["TransactionMonth"].dt.month - df["CohortMonth"].dt.month)
    +
    1
)

#20 Final duplicate check

In [69]:
df = df.drop_duplicates().copy()

#21 Check final missing values

In [70]:
df.isnull().sum()

InvoiceNo             0
CustomerID            0
InvoiceDate           0
Quantity              0
UnitPrice             0
DiscountPercent       0
Revenue               0
ProductCategory       0
Country               0
Region                0
AcquisitionChannel    0
SubscriptionPlan      0
OrderStatus           0
PaymentMethod         0
TransactionMonth      0
CohortMonth           0
CohortIndex           0
dtype: int64

#22 Final data types

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3682 entries, 1 to 4139
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   InvoiceNo           3682 non-null   object
 1   CustomerID          3682 non-null   object
 2   InvoiceDate         3682 non-null   datetime64[ns]
 3   Quantity            3682 non-null   int64
 4   UnitPrice           3682 non-null   float64
 5   DiscountPercent     3682 non-null   int64
 6   Revenue             3682 non-null   float64
 7   ProductCategory     3682 non-null   object
 8   Country             3682 non-null   object
 9   Region              3682 non-null   object
 10  AcquisitionChannel  3682 non-null   object
 11  SubscriptionPlan    3682 non-null   object
 12  OrderStatus         3682 non-null   object
 13  PaymentMethod       3682 non-null   object
 14  TransactionMonth    3682 non-null   datetime64[ns]
 15  CohortMonth         3682 non-null   datetime64[ns]
 16  CohortIndex         3682 non-null   int32
dtypes: datetime64[ns](3), float64(2), int32(1), int64(2), object(9)
memory usage: 503.4+ KB

In [72]:
df["CohortIndex"] = df["CohortIndex"].astype(int)

#23 Create a cleaning summary

In [73]:
summary = {
    "Final Rows": len(df),
    "Unique Customers": df["CustomerID"].nunique(),
    "Unique Orders": df["InvoiceNo"].nunique(),
    "Total Revenue": round(df["Revenue"].sum(), 2),
    "Start Date": df["InvoiceDate"].min(),
    "End Date": df["InvoiceDate"].max()
}

summary

{'Final Rows': 3682,
 'Unique Customers': 1157,
 'Unique Orders': 3682,
 'Total Revenue': np.float64(12839490.24),
 'Start Date': Timestamp('2025-01-09 00:00:00'),
 'End Date': Timestamp('2026-06-30 00:00:00')}

#24 Export cleaned dataset

In [74]:
df.to_csv(
    "cleaned_customer_transactions.csv",
    index=False
)

In [75]:
from google.colab import files

files.download(
    "cleaned_customer_transactions.csv"
)